//! Compiles `vocabulary/` into the library.
//!
//! Reads every `vocabulary/<market>/<table>.toml` and every
//! `vocabulary/language/<code>/<table>.toml`, checks them, and writes the
//! entries out as Rust source that `src/vocabulary.rs` includes. The library
//! never sees a TOML file: by the time it is compiled, the vocabulary is a set
//! of static slices, so there is nothing to load, nothing to be missing and
//! nothing to fail to parse in production. A broken entry fails the build
//! instead, and the message names the file and line.
//!
//! This is the only code in the crate that touches the file system. It runs
//! at compile time, on the machine doing the build, and what it produces is
//! static — so the lints in clippy.toml that keep I/O out of the core are
//! allowed here, and nowhere else.

#![allow(clippy::disallowed_methods, clippy::disallowed_types)]

use std::fmt::Write as _;
use std::path::Path;
use std::{env, fs, io, process};

// The library's own `Market`, `Language` and `Unit`, so each list is written
// down once. The build script uses only `ALL` and `code()`.
#[allow(dead_code)]
#[path = "src/language.rs"]
mod language;
#[allow(dead_code)]
#[path = "src/market.rs"]
mod market;
#[allow(dead_code)]
#[path = "src/unit.rs"]
mod unit;

#[path = "codegen/layout.rs"]
mod layout;
#[path = "codegen/table.rs"]
mod table;
#[path = "codegen/units.rs"]
mod units;

use language::Language;
use market::Market;
use unit::Unit;

/// Every table a market has. Each name must be a field of `Vocabulary`, and
/// every field must be named here: the generated code does not compile
/// otherwise, so the two cannot drift apart.
const TABLES: &[&str] = &["abbreviations", "units", "categories", "category_vat"];

/// Every table a language can have, each a field of `LanguageVocabulary`.
/// A language has only the ones someone has written for it.
const LANGUAGE_TABLES: &[&str] = &["units"];

fn main() {
    // Cargo scans the whole directory, so adding, editing, renaming or
    // deleting any file under it reruns this script.
    println!("cargo::rerun-if-changed=vocabulary");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR");
    let root = Path::new(&manifest_dir).join("vocabulary");
    let markets: Vec<&str> = Market::ALL.iter().map(|market| market.code()).collect();
    let languages: Vec<&str> = Language::ALL
        .iter()
        .map(|language| language.code())
        .collect();
    let unit_codes: Vec<&str> = Unit::ALL.iter().map(|unit| unit.code()).collect();
    let symbols: Vec<&str> = Unit::ALL
        .iter()
        .filter(|unit| **unit != Unit::Piece)
        .map(|unit| unit.code())
        .collect();

    let mut files = Vec::new();
    list_files(&root, "", &mut files);
    files.sort();
    let mut problems = layout::problems(
        &files,
        &layout::Expected {
            markets: &markets,
            tables: TABLES,
            languages: &languages,
            language_tables: LANGUAGE_TABLES,
        },
    );

    let mut generated = String::from(
        "// @generated by mangel/build.rs from mangel/vocabulary/.\n\
         // Edit the TOML files, not this one.\n\n",
    );

    for market in Market::ALL {
        let _ = writeln!(
            generated,
            "static {}: Vocabulary = Vocabulary {{",
            constant(market.code())
        );
        for table_name in TABLES {
            let relative = format!("vocabulary/{}/{table_name}.toml", market.code());
            let path = root.join(market.code()).join(format!("{table_name}.toml"));
            // A missing market table is already reported by `layout`.
            let entries = read_table(&path, &relative, &mut problems).unwrap_or_default();
            let _ = writeln!(generated, "    {table_name}: &[");
            if *table_name == "units" {
                for problem in units::market_problems(&entries, &unit_codes) {
                    problems.push(format!("{relative}: {problem}"));
                }
                for (code, spelling) in &entries {
                    if let Some(unit) = Unit::from_code(code) {
                        let _ = writeln!(generated, "        (Unit::{unit:?}, {spelling:?}),");
                    }
                }
            } else {
                for (word, replacement) in &entries {
                    // `{:?}` on a str is a valid Rust string literal, escapes included.
                    let _ = writeln!(generated, "        ({word:?}, {replacement:?}),");
                }
            }
            let _ = writeln!(generated, "    ],");
        }
        let _ = writeln!(generated, "}};\n");
    }

    for language in Language::ALL {
        let _ = writeln!(
            generated,
            "static LANGUAGE_{}: LanguageVocabulary = LanguageVocabulary {{",
            constant(language.code())
        );
        for table_name in LANGUAGE_TABLES {
            let relative = format!(
                "vocabulary/{}/{}/{table_name}.toml",
                layout::LANGUAGE_DIR,
                language.code()
            );
            let path = root
                .join(layout::LANGUAGE_DIR)
                .join(language.code())
                .join(format!("{table_name}.toml"));
            // A language without this table has no words in it yet.
            let entries = read_table(&path, &relative, &mut problems).unwrap_or_default();
            for problem in units::language_problems(&entries, &unit_codes, &symbols) {
                problems.push(format!("{relative}: {problem}"));
            }
            let _ = writeln!(generated, "    {table_name}: &[");
            for (word, code) in &entries {
                if let Some(unit) = Unit::from_code(code) {
                    let _ = writeln!(generated, "        ({word:?}, Unit::{unit:?}),");
                }
            }
            let _ = writeln!(generated, "    ],");
        }
        let _ = writeln!(generated, "}};\n");
    }

    let _ = writeln!(
        generated,
        "pub(crate) fn of(market: Market) -> &'static Vocabulary {{"
    );
    let _ = writeln!(generated, "    match market {{");
    for market in Market::ALL {
        let _ = writeln!(
            generated,
            "        Market::{market:?} => &{},",
            constant(market.code())
        );
    }
    let _ = writeln!(generated, "    }}\n}}\n");
    let _ = writeln!(
        generated,
        "pub(crate) fn of_language(language: Language) -> &'static LanguageVocabulary {{"
    );
    let _ = writeln!(generated, "    match language {{");
    for language in Language::ALL {
        let _ = writeln!(
            generated,
            "        Language::{language:?} => &LANGUAGE_{},",
            constant(language.code())
        );
    }
    let _ = writeln!(generated, "    }}\n}}");

    if !problems.is_empty() {
        for problem in &problems {
            println!("cargo::error={problem}");
        }
        println!(
            "cargo::error=mangel's vocabulary has {} problem(s). See mangel/vocabulary/README.md.",
            problems.len()
        );
        process::exit(1);
    }

    let out_dir = env::var("OUT_DIR").expect("cargo sets OUT_DIR");
    let out = Path::new(&out_dir).join("vocabulary.rs");
    fs::write(&out, generated).unwrap_or_else(|error| panic!("writing {}: {error}", out.display()));
}

/// The entries of one table, or `None` when the file does not exist. Every
/// problem with a file that does exist is added to `problems`, by file and
/// line, and its entries come back empty.
fn read_table(
    path: &Path,
    relative: &str,
    problems: &mut Vec<String>,
) -> Option<Vec<table::Entry>> {
    match fs::read_to_string(path) {
        Ok(source) => Some(table::read(&source).unwrap_or_else(|found| {
            problems.extend(found.into_iter().map(|problem| match problem.line {
                Some(line) => format!("{relative}, line {line}: {}", problem.message),
                None => format!("{relative}: {}", problem.message),
            }));
            Vec::new()
        })),
        Err(error) if error.kind() == io::ErrorKind::NotFound => None,
        Err(error) if error.kind() == io::ErrorKind::InvalidData => {
            problems.push(format!(
                "{relative} is not saved as UTF-8. Save it again with UTF-8 encoding."
            ));
            Some(Vec::new())
        }
        Err(error) => {
            problems.push(format!("{relative} could not be read: {error}"));
            Some(Vec::new())
        }
    }
}

/// Every file under `dir`, as a `/`-separated path relative to the vocabulary
/// root. A missing root yields nothing; `layout` then reports every table as
/// missing, which is the useful message.
fn list_files(dir: &Path, prefix: &str, files: &mut Vec<String>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let name = entry.file_name().to_string_lossy().into_owned();
        let relative = format!("{prefix}{name}");
        if entry.file_type().is_ok_and(|kind| kind.is_dir()) {
            list_files(&entry.path(), &format!("{relative}/"), files);
        } else {
            files.push(relative);
        }
    }
}

fn constant(code: &str) -> String {
    code.to_uppercase()
}
